image: node:18-alpine

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - yarn install
  - yarn build
  except:
    - main

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
    - build
  only:
    - main

