variables:
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/.yarn/cache"
  YARN_ENABLE_GLOBAL_CACHE: "false"

default:
  image: 'europe-north1-docker.pkg.dev/holi-shared/docker-hub-remote/node:23-slim'
  tags:
    - 1cpu-4gb
  before_script:
    - set -ex
    # env -0 | sort -z | tr '\0' '\n': Sort env output alphabetically, keeping multiline variables intact
    # egrep: Remove sensitive information from the output of env
    - env -0 | sort -z | tr '\0' '\n' | egrep -ve '^(DOCKER_AUTH_CONFIG|GOOGLE_APPLICATION_CREDENTIALS)=.*'
    - corepack enable

.yarn-cache-rw:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn/
  policy: pull-push

.yarn-cache-readonly:
  key:
    files:
      - yarn.lock
  paths:
    - .yarn/
  policy: pull

stages:
  - prepare
  - build

install_deps:
  stage: prepare
  cache: !reference [.yarn-cache-rw]
  script:
    - yarn install --immutable
  rules:
    - if: $CI_COMMIT_BRANCH
      changes: 
      - yarn.lock

.build:
  stage: build
  needs: 
    - job: install_deps
      optional: true
  cache: !reference [.yarn-cache-readonly]
  script:
    - yarn install --immutable --immutable-cache
    - yarn graphql-to-doc
    - yarn build

test:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != 'main'

pages:
  extends: .build
  after_script:
    - mv build/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

