image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

default:
  before_script:
    - set -eux
    - env
#  artifacts:
#    paths:
#      - what's a good build log artifact for jekyll?
#    name: "${CI_JOB_NAME}_${CI_JOB_ID}"
#    when: on_failure
  interruptible: true
  tags:
    - holi-small # build on smaller machine

test:
  stage: test
  script:
  - bundle install
  - bundle exec jekyll build -d test
  artifacts:
    paths:
    - test
  except:
  - main

pages:
  stage: deploy
  script:
  - bundle install
  - bundle exec jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - main
